require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PriceCurveNymexesController do

  # This should return the minimal set of attributes required to create a valid
  # PriceCurveNymex. As you add validations to PriceCurveNymex, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "month_year" => "2013-10-22 12:14:50" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PriceCurveNymexesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all price_curve_nymexes as @price_curve_nymexes" do
      price_curve_nymex = PriceCurveNymex.create! valid_attributes
      get :index, {}, valid_session
      assigns(:price_curve_nymexes).should eq([price_curve_nymex])
    end
  end

  describe "GET show" do
    it "assigns the requested price_curve_nymex as @price_curve_nymex" do
      price_curve_nymex = PriceCurveNymex.create! valid_attributes
      get :show, {:id => price_curve_nymex.to_param}, valid_session
      assigns(:price_curve_nymex).should eq(price_curve_nymex)
    end
  end

  describe "GET new" do
    it "assigns a new price_curve_nymex as @price_curve_nymex" do
      get :new, {}, valid_session
      assigns(:price_curve_nymex).should be_a_new(PriceCurveNymex)
    end
  end

  describe "GET edit" do
    # it "assigns the requested price_curve_nymex as @price_curve_nymex" do
#       price_curve_nymex = PriceCurveNymex.create! valid_attributes
#       get :edit, {:id => price_curve_nymex.to_param}, valid_session
#       assigns(:price_curve_nymex).should eq(price_curve_nymex)
#     end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PriceCurveNymex" do
        expect {
          post :create, {:price_curve_nymex => valid_attributes}, valid_session
        }.to change(PriceCurveNymex, :count).by(1)
      end

      it "assigns a newly created price_curve_nymex as @price_curve_nymex" do
        post :create, {:price_curve_nymex => valid_attributes}, valid_session
        assigns(:price_curve_nymex).should be_a(PriceCurveNymex)
        assigns(:price_curve_nymex).should be_persisted
      end

      it "redirects to the created price_curve_nymex" do
        post :create, {:price_curve_nymex => valid_attributes}, valid_session
        response.should redirect_to(PriceCurveNymex.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved price_curve_nymex as @price_curve_nymex" do
        # Trigger the behavior that occurs when invalid params are submitted
        PriceCurveNymex.any_instance.stub(:save).and_return(false)
        post :create, {:price_curve_nymex => { "month_year" => "invalid value" }}, valid_session
        assigns(:price_curve_nymex).should be_a_new(PriceCurveNymex)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PriceCurveNymex.any_instance.stub(:save).and_return(false)
        post :create, {:price_curve_nymex => { "month_year" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested price_curve_nymex" do
        price_curve_nymex = PriceCurveNymex.create! valid_attributes
        # Assuming there are no other price_curve_nymexes in the database, this
        # specifies that the PriceCurveNymex created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PriceCurveNymex.any_instance.should_receive(:update).with({ "month_year" => "2013-10-22 12:14:50" })
        put :update, {:id => price_curve_nymex.to_param, :price_curve_nymex => { "month_year" => "2013-10-22 12:14:50" }}, valid_session
      end

      it "assigns the requested price_curve_nymex as @price_curve_nymex" do
        price_curve_nymex = PriceCurveNymex.create! valid_attributes
        put :update, {:id => price_curve_nymex.to_param, :price_curve_nymex => valid_attributes}, valid_session
        assigns(:price_curve_nymex).should eq(price_curve_nymex)
      end

      it "redirects to the price_curve_nymex" do
        price_curve_nymex = PriceCurveNymex.create! valid_attributes
        put :update, {:id => price_curve_nymex.to_param, :price_curve_nymex => valid_attributes}, valid_session
        response.should redirect_to(price_curve_nymex)
      end
    end

    describe "with invalid params" do
      it "assigns the price_curve_nymex as @price_curve_nymex" do
        price_curve_nymex = PriceCurveNymex.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PriceCurveNymex.any_instance.stub(:save).and_return(false)
        put :update, {:id => price_curve_nymex.to_param, :price_curve_nymex => { "month_year" => "invalid value" }}, valid_session
        assigns(:price_curve_nymex).should eq(price_curve_nymex)
      end

      it "re-renders the 'edit' template" do
        price_curve_nymex = PriceCurveNymex.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PriceCurveNymex.any_instance.stub(:save).and_return(false)
        put :update, {:id => price_curve_nymex.to_param, :price_curve_nymex => { "month_year" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested price_curve_nymex" do
      price_curve_nymex = PriceCurveNymex.create! valid_attributes
      expect {
        delete :destroy, {:id => price_curve_nymex.to_param}, valid_session
      }.to change(PriceCurveNymex, :count).by(-1)
    end

    it "redirects to the price_curve_nymexes list" do
      price_curve_nymex = PriceCurveNymex.create! valid_attributes
      delete :destroy, {:id => price_curve_nymex.to_param}, valid_session
      response.should redirect_to(price_curve_nymexes_url)
    end
  end

end
